import { AppStateData } from "./models/types";

export const sampleState: AppStateData = {
  floor: { width: 120, length: 80 },
  grid: { show: true, snap: true, size: 1 },
  lastModified: Date.now(),
  nodes: [
    {
      id: "node-work-1",
      type: "workstation",
      name: "Assembly 1",
      x: 10,
      y: 10,
      w: 12,
      h: 8,
      rotationDeg: 0,
      props: { tools: ["Torque wrench", "Screwdriver"] },
    },
    {
      id: "node-shelf-1",
      type: "shelf",
      name: "Shelf A",
      x: 30,
      y: 12,
      w: 10,
      h: 6,
      rotationDeg: 0,
      props: { inventory: ["Brackets", "Bolts"] },
    },
    {
      id: "node-dock-1",
      type: "dock",
      name: "Dock 1",
      x: 80,
      y: 10,
      w: 20,
      h: 12,
      rotationDeg: 0,
      props: { zones: ["Zone A", "Zone B"] },
    },
    {
      id: "node-lane-in",
      type: "lane",
      name: "Inbound Lane",
      x: 80,
      y: 26,
      w: 20,
      h: 6,
      rotationDeg: 0,
      props: { laneDirection: "inbound" },
    },
    {
      id: "node-door-bay",
      type: "door",
      name: "Bay Door 1",
      x: 105,
      y: 10,
      w: 6,
      h: 4,
      rotationDeg: 0,
      props: { doorKind: "bay", doorStyle: "double" },
    },
    {
      id: "node-person-1",
      type: "person",
      name: "Operator",
      x: 16,
      y: 30,
      w: 4,
      h: 4,
      rotationDeg: 0,
      props: {},
    },
  ],
  flows: [
    {
      id: "flow-prod-1",
      type: "product",
      name: "Parts to Assembly",
      fromNodeId: "node-shelf-1",
      toNodeId: "node-work-1",
      waypoints: [{ x: 25, y: 15 }],
    },
    {
      id: "flow-person-1",
      type: "person",
      name: "Operator Route",
      fromNodeId: "node-person-1",
      toNodeId: "node-work-1",
      waypoints: [{ x: 20, y: 24 }, { x: 14, y: 20 }],
    },
  ],
};
